//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalentineV2.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalentineV2.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRİZMATİK BALYA MAKİNESİ.
        /// </summary>
        internal static string Footer_PrismaticBaler {
            get {
                return ResourceManager.GetString("Footer_PrismaticBaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string Lang_EN {
            get {
                return ResourceManager.GetString("Lang_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seç.
        /// </summary>
        internal static string Lang_Select {
            get {
                return ResourceManager.GetString("Lang_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string Lang_TR {
            get {
                return ResourceManager.GetString("Lang_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        internal static string Menu_Camera {
            get {
                return ResourceManager.GetString("Menu_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Ayarları.
        /// </summary>
        internal static string Menu_Fan {
            get {
                return ResourceManager.GetString("Menu_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem Değeri.
        /// </summary>
        internal static string Menu_Humidity {
            get {
                return ResourceManager.GetString("Menu_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidrolik.
        /// </summary>
        internal static string Menu_Hydraulic {
            get {
                return ResourceManager.GetString("Menu_Hydraulic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamba.
        /// </summary>
        internal static string Menu_Lamp {
            get {
                return ResourceManager.GetString("Menu_Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yağlama.
        /// </summary>
        internal static string Menu_Lubrication {
            get {
                return ResourceManager.GetString("Menu_Lubrication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzleme.
        /// </summary>
        internal static string Menu_Monitoring {
            get {
                return ResourceManager.GetString("Menu_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tartı.
        /// </summary>
        internal static string Menu_Scale {
            get {
                return ResourceManager.GetString("Menu_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balya bağlandı.
        /// </summary>
        internal static string Notice_BaleTied {
            get {
                return ResourceManager.GetString("Notice_BaleTied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İP KOPTU.
        /// </summary>
        internal static string Notice_IpLost {
            get {
                return ResourceManager.GetString("Notice_IpLost", resourceCulture);
            }
        }
    }
}
